<dl>
    <?php if ($this->getCheckout()->getStepData('excellence', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('excellence', 'complete')): ?>
            <dt class="complete">
                <?php echo $this->__('Excellence Review') ?> <span class="separator">|</span> <a href="#excellence" onclick="checkout.accordion.openSection('opc-excellence'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <div>
                    <?php echo $this->__('Excellence Review Is: ');?>
                    <?php
                    $like = $this->getQuote()->getExcellenceLike();
                    if($like == 1){
                        echo $this->__('Yes');
                    } else{
                        echo $this->__('No');
                    }
                    ?>
                </div>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Excellence Review') ?>
            </dt>
        <?php endif; ?>
    <?php endif; ?>
